services:

  app:
    container_name: laravel-app
    build: .
    volumes:
      - ../laravel-app:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: la_interview
    volumes:
      - ../docker/mysql:/var/lib/mysql
      - ../docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 3306:3306

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

#docker compose -p la10-invoice up -d
